import type { Metadata } from "next";
import "./globals.css";

import QueryProvider from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <QueryProvider>
          <div className="h-full">
            <div className="flex flex-col min-h-screen bg-base-200">
              <div className="mockup-browser bg-base-300 border w-full max-w-xl mx-auto my-16">
                <div className="mockup-browser-toolbar">
                  <div className="input">https://daisyui.com</div>
                </div>
                {children}
              </div>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
