import type { Metadata } from "next";
import "./globals.css";

import QueryProvider from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <QueryProvider>
          <div className="h-full">
            <div className="flex flex-col min-h-screen">
              {children}
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
